export const SIGNUP = "SIGNUP";
export const SIGNUP_EMAIL_EXIST = "SIGNUP_EMAIL_EXIST";
export const SIGNUP_USERNAME_EXIST = "SIGNUP_USERNAME_EXIST";
export const REFERRAL_CODE_EXIST = "REFERRAL_CODE_EXIST";
export const LOGIN = "LOGIN";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGOUT = "LOGOUT";
export const GET_FEED = "GET_FEED";
export const GET_VIDEO = "GET_VIDEO";
export const CLEAR_VIDEO = "CLEAR_VIDEO";
export const UPDATE_VIDEO = "UPDATE_VIDEO";
export const DELETE_VIDEO = "DELETE_VIDEO";
export const ADD_COMMENT = "ADD_COMMENT";
export const GET_PROFILE = "GET_PROFILE";
export const CLEAR_PROFILE = "CLEAR_PROFILE";
export const UPDATE_PROFILE = "UPDATE_PROFILE";

export const GET_NOTIFICATIONS_CATEGORIES = "GET_NOTIFICATIONS_CATEGORIES";

export const GET_NOTIFICATIONS = "GET_NOTIFICATIONS";
export const CLEAR_NOTIFICATIONS = "CLEAR_NOTIFICATIONS";
export const GET_NOTIFICATION_COMMENT_ID = "GET_NOTIFICATION_COMMENT_ID";
export const SET_FETCHING = "SET_FETCHING";
export const CLEAR_COMMENT_ID = "CLEAR_COMMENT_ID";
export const INCREMENT_NOTIFICATION_COUNT = "INCREMENT_NOTIFICATION_COUNT";
export const NOTIFICATIONS_READ_COUNT = "NOTIFICATIONS_READ_COUNT";

export const OPEN_SIDEBAR = "OPEN_SIDEBAR";
export const CLOSE_SIDEBAR = "CLOSE_SIDEBAR";
export const GET_CHANNEL_RECOMMENDATIONS = "GET_CHANNEL_RECOMMENDATIONS";
export const SUBSCRIBE_FROM_VIDEO = "SUBSCRIBE_FROM_VIDEO";
export const UNSUBSCRIBE_FROM_VIDEO = "UNSUBSCRIBE_FROM_VIDEO";
export const LIKE = "LIKE";
export const CANCEL_LIKE = "UNLIKE";
export const DISLIKE = "DISLIKE";
export const CANCEL_DISLIKE = "CANCEL_DISLIKE";
export const SUBSCRIBE_FROM_PROFILE = "SUBSCRIBE_FROM_PROFILE";
export const UNSUBSCRIBE_FROM_PROFILE = "UNSUBSCRIBE_FROM_PROFILE";
export const GET_SEARCH_RESULTS = "GET_SEARCH_RESULTS";
export const CLEAR_SEARCH_RESULTS = "CLEAR_SEARCH_RESULTS";
export const ADD_CHANNEL = "ADD_CHANNEL";
export const REMOVE_CHANNEL = "REMOVE_CHANNEL";
export const GET_LIKED_VIDEOS = "GET_LIKED_VIDEOS";
export const UPDATE_USER = "UPDATE_USER";
export const ADD_TO_LIKED_VIDEOS = "ADD_TO_LIKED_VIDEOS";
export const REMOVE_FROM_LIKED_VIDEOS = "REMOVE_FROM_LIKED_VIDEOS";
export const ADD_TO_RECOMMENDATIONS = "ADD_TO_RECOMMENDATIONS";
export const SUBSCRIBE_FROM_SEARCH_RESULTS = "SUBSCRIBE_FROM_SEARH_RESULTS";
export const UNSUBSCRIBE_FROM_SEARCH_RESULTS = "UNSUBSCRIBE_FROM_SEARH_RESULTS";
export const GET_HISTORY = "GET_HISTORY";
export const ADD_TO_HISTORY = "ADD_TO_HISTORY";
export const SHOW_NOT_FOUND = "SHOW_NOT_FOUND";
export const CLEAR_NOT_FOUND = "CLEAR_NOT_FOUND";

export const STRIPE_ONBOARD = "STRIPE_ONBOARD";
export const ACCEPT_PAYMENT_SUCCESS = "ACCEPT_PAYMENT_SUCCESS";
export const TRANSFERS_AMOUNT = "TRANSFERS_AMOUNT";
export const CREATE_CUSTOMER = "CREATE_CUSTOMER";

export const SUBSCRIBE_FROM_CHANNEL_RECOMMENDATIONS =
  "SUBSCRIBE_FROM_CHANNEL_RECOMMENDATIONS";
export const UNSUBSCRIBE_FROM_CHANNEL_RECOMMENDATIONS =
  "UNSUBSCRIBE_FROM_CHANNEL_RECOMMENDATIONS";

export const GET_VIDEO_CATEGORIES = "GET_VIDEO_CATEGORIES";
export const GET_VIDEO_ACCESS_OVERLAYS = "GET_VIDEO_ACCESS_OVERLAYS";

export const GET_HASHTAGS = "GET_HASHTAGS";

// videos for sections types
export const GET_LATEST_VIDEOS = "GET_LATEST_VIDEOS";
export const GET_TRENDING = "GET_TRENDING";
export const GET_RECOMMENDATIONS = "GET_RECOMMENDATIONS";
export const GET_FEATURED = "GET_FEATURED";
export const GET_STAFF_PICK = "GET_STAFF_PICK";
export const GET_VIDEOS_FEATURED = "GET_VIDEOS_FEATURED";
export const GET_VIDEOS_STAFF_PICK = "GET_VIDEOS_STAFF_PICK";
export const GET_VIDEOS_BY_CATEGORY = "GET_VIDEOS_BY_CATEGORY";

export const GET_ALL_STORAGE = "GET_ALL_STORAGE";
export const GET_SINGLE_STORAGE = "GET_SINGLE_STORAGE";
export const GET_ALL_USER_SETTINGS = "GET_ALL_USER_SETTINGS";
export const GET_USER_SETTING_BY_USERID = "GET_USER_SETTING_BY_USERID";
export const UPDATE_USER_SETTING = "UPDATE_USER_SETTING";
export const UPDATE_USER_SETTING_REQUEST = "UPDATE_USER_SETTING_REQUEST";
export const GET_ALL_BADGES = "GET_ALL_BADGES";
// Emailer Types
export const VERIFY_EMAIL_REQUEST = "VERIFY_EMAIL_REQUEST";
export const VERIFY_EMAIL_SUCCESS = "VERIFY_EMAIL_SUCCESS";
export const VERIFY_EMAIL_FAILED = "VERIFY_EMAIL_FAILED";
export const GET_BADGES_BY_USERROLE = "GET_BADGES_BY_USERROLE";
export const GET_USER_BY_ID = "GET_US ER_BY_ID";
//Reset Password
export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAILED = "RESET_PASSWORD_FAILED";
export const CHANGE_PASSWORD_REQUEST = "CHANGE_PASSWORD_REQUEST";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_FAILED = "CHANGE_PASSWORD_FAILED";
export const MORE_FROM_USER = "MORE_FROM_USER";
export const GET_CATEGORY_BY_ID = "GET_CATEGORY_BY_ID";
export const SET_EMAIL_EXISTS_FALSE = "SET_EMAIL_EXISTS_FALSE";
export const VISIT_STRIPE_CUSTOMER_PORTAL_REQUEST =
  "VISIT_STRIPE_CUSTOMER_PORTAL_REQUEST";
export const VISIT_STRIPE_CUSTOMER_PORTAL_SUCCESS =
  "VISIT_STRIPE_CUSTOMER_PORTAL_SUCCESS";
export const VISIT_STRIPE_CUSTOMER_PORTAL_FAILED =
  "VISIT_STRIPE_CUSTOMER_PORTAL_FAILED";
export const UNLOCK_WATCH_VIDEO = "UNLOCK_WATCH_VIDEO";
export const UNLOCK_FEATURED_VIDEO = "UNLOCK_FEATURED_VIDEO";
export const UNLOCK_TRENDING_VIDEO = "UNLOCK_TRENDING_VIDEO";
export const UNLOCK_LATEST_VIDEO = "UNLOCK_LATEST_VIDEO";
export const UNLOCK_STAFF_PICK_VIDEO = "UNLOCK_STAFF_PICK_VIDEO";
export const UNLOCK_CATEGORY_FEATURED_VIDEO = "UNLOCK_CATEGORY_FEATURED_VIDEO";
export const UNLOCK_CATEGORY_VIDEO = "UNLOCK_CATEGORY_VIDEO";
export const UNLOCK_CATEGORY_STAFF_PICK_VIDEO =
  "UNLOCK_CATEGORY_STAFF_PICK_VIDEO";
export const UNLOCK_MORE_VIDEO = "UNLOCK_MORE_VIDEO";
export const UNLOCK_LIKE_VIDEO = "UNLOCK_LIKE_VIDEO";
export const UNLOCK_SEARCH_VIDEO = "UNLOCK_SEARCH_VIDEO";
export const UNLOCK_PROFILE_VIDEO = "UNLOCK_PROFILE_VIDEO";
export const GET_USER_TRANSACTIONS_REQ = "GET_USER_TRANSACTIONS_REQ";
export const GET_USER_TRANSACTIONS = "GET_USER_TRANSACTIONS";
export const GET_USER_TRANSACTIONS_FAILED = "GET_USER_TRANSACTIONS_FAILED";

// karma sent by user
export const GET_KARMA_SENT_REQ = "GET_KARMA_SENT_REQ";
export const GET_KARMA_SENT_TRANSACTIONS = "GET_KARMA_SENT_TRANSACTIONS";
export const GET_KARMA_SENT_TRANSACTIONS_FAILED =
  "GET_KARMA_SENT_TRANSACTIONS_FAILED";

export const SET_FILTERED_DATA = "SET_FILTERED_DATA";

// warrior banner type
export const GET_WARRIOR_SLIDER = "GET_WARRIOR_SLIDER";
export const GET_FEATURED_WARRIORS = "GET_FEATURED_WARRIORS";

// contact us
export const SEND_CONTACT_US_EMAIL_REQ = "SEND_CONTACT_US_EMAIL_REQ";
export const SEND_CONTACT_US_EMAIL_SUCCESS = "SEND_CONTACT_US_EMAIL_SUCCESS";
export const SEND_CONTACT_US_EMAIL_FAILED = "SEND_CONTACT_US_EMAIL_FAILED";
export const RESET_CONTACT_US = "RESET_CONTACT_US";

// library page
export const GET_LIBRARY_VIDEOS = "GET_LIBRARY_VIDEOS";

// delete user
export const DELETE_USER = "DELETE_USER";

// get marketing banner
export const GET_MARKETING_BANNERS = "GET_MARKETING_BANNERS";
// clear marketing banner
export const CLEAR_MARKETING_BANNERS = "CLEAR_MARKETING_BANNERS";
//Tip After Two
export const UNLOCK_TAT_VIDEO = "UNLOCK_TAT_VIDEO";
//check if password reset token is expired
export const CHECK_EXPIRED_PW_RESET_TOKEN = "CHECK_EXPIRED_PW_RESET_TOKEN";
export const PW_RESET_TOKEN_EXPIRED = "PW_RESET_TOKEN_EXPIRED";

export const CLEAR_RESET_PASSWORD_ERROR = "CLEAR_RESET_PASSWORD_ERROR";

// new category request
export const NEW_CATEGORY_REQUEST = "NEW_CATEGORY_REQUEST";
export const NEW_CATEGORY_SUCCESS = "NEW_CATEGORY_SUCCESS";
export const NEW_CATEGORY_FAIL = "NEW_CATEGORY_FAIL";

// new content flag
export const NEW_CONTENT_FLAG_REQUEST = "NEW_CONTENT_FLAG_REQUEST";
export const NEW_CONTENT_FLAG_SUCCESS = "NEW_CONTENT_FLAG_SUCCESS";
export const NEW_CONTENT_FLAG_FAIL = "NEW_CONTENT_FLAG_FAIL";

// get flag types
export const GET_FLAG_TYPES_REQUEST = "GET_FLAG_TYPES_REQUEST";
export const GET_FLAG_TYPES_SUCCESS = "GET_FLAG_TYPES_SUCCESS";
export const GET_FLAG_TYPES_FAIL = "GET_FLAG_TYPES_FAIL";

// create new playlist
export const CREATE_NEW_PLAYLIST_REQUEST = "CREATE_NEW_PLAYLIST_REQUEST";
export const CREATE_NEW_PLAYLIST_SUCCESS = "CREATE_NEW_PLAYLIST_SUCCESS";
export const CREATE_NEW_PLAYLIST_FAIL = "CREATE_NEW_PLAYLIST_FAIL";

// delete playlist
export const DELETE_PLAYLIST_REQUEST = "DELETE_PLAYLIST_REQUEST";
export const DELETE_PLAYLIST_SUCCESS = "DELETE_PLAYLIST_SUCCESS";
export const DELETE_PLAYLIST_FAIL = "DELETE_PLAYLIST_FAIL";

// edit playlist
export const EDIT_PLAYLIST_REQUEST = "EDIT_PLAYLIST_REQUEST";
export const EDIT_PLAYLIST_SUCCESS = "EDIT_PLAYLIST_SUCCESS";
export const EDIT_PLAYLIST_FAIL = "EDIT_PLAYLIST_FAIL";

// get all playlist
export const GET_ALL_PLAYLIST_REQUEST = "GET_ALL_PLAYLIST_REQUEST";
export const GET_ALL_PLAYLIST_SUCCESS = "GET_ALL_PLAYLIST_SUCCESS";
export const GET_ALL_PLAYLIST_FAIL = "GET_ALL_PLAYLIST_FAIL";

// get single playlist
export const GET_SINGLE_PLAYLIST_REQUEST = "GET_SINGLE_PLAYLIST_REQUEST";
export const GET_SINGLE_PLAYLIST_SUCCESS = "GET_SINGLE_PLAYLIST_SUCCESS";
export const GET_SINGLE_PLAYLIST_FAIL = "GET_SINGLE_PLAYLIST_FAIL";

// add video to playlist
export const ADD_VIDEO_TO_PLAYLIST_REQUEST = "ADD_VIDEO_TO_PLAYLIST_REQUEST";
export const ADD_VIDEO_TO_PLAYLIST_SUCCESS = "ADD_VIDEO_TO_PLAYLIST_SUCCESS";
export const ADD_VIDEO_TO_PLAYLIST_FAIL = "ADD_VIDEO_TO_PLAYLIST_FAIL";
export const ADD_VIDEO_TO_PLAYLIST_RESET = "ADD_VIDEO_TO_PLAYLIST_RESET";

// remove video from playlist
export const REMOVE_VIDEO_FROM_PLAYLIST_REQUEST =
  "REMOVE_VIDEO_FROM_PLAYLIST_REQUEST";
export const REMOVE_VIDEO_FROM_PLAYLIST_SUCCESS =
  "REMOVE_VIDEO_FROM_PLAYLIST_SUCCESS";
export const REMOVE_VIDEO_FROM_PLAYLIST_FAIL =
  "REMOVE_VIDEO_FROM_PLAYLIST_FAIL";
export const REMOVE_VIDEO_FROM_PLAYLIST_RESET =
  "REMOVE_VIDEO_FROM_PLAYLIST_RESET";

// create new series
export const CREATE_NEW_SERIES_REQUEST = "CREATE_NEW_SERIES_REQUEST";
export const CREATE_NEW_SERIES_SUCCESS = "CREATE_NEW_SERIES_SUCCESS";
export const CREATE_NEW_SERIES_FAIL = "CREATE_NEW_SERIES_FAIL";

// delete series
export const DELETE_SERIES_REQUEST = "DELETE_SERIES_REQUEST";
export const DELETE_SERIES_SUCCESS = "DELETE_SERIES_SUCCESS";
export const DELETE_SERIES_FAIL = "DELETE_SERIES_FAIL";

// edit series
export const EDIT_SERIES_REQUEST = "EDIT_SERIES_REQUEST";
export const EDIT_SERIES_SUCCESS = "EDIT_SERIES_SUCCESS";
export const EDIT_SERIES_FAIL = "EDIT_SERIES_FAIL";

// get all series of user
export const GET_ALL_SERIES_OF_USER_REQUEST = "GET_ALL_SERIES_OF_USER_REQUEST";
export const GET_ALL_SERIES_OF_USER_SUCCESS = "GET_ALL_SERIES_OF_USER_SUCCESS";
export const GET_ALL_SERIES_OF_USER_FAIL = "GET_ALL_SERIES_OF_USER_FAIL";

// get single series
export const GET_SINGLE_SERIES_REQUEST = "GET_SINGLE_SERIES_REQUEST";
export const GET_SINGLE_SERIES_SUCCESS = "GET_SINGLE_SERIES_SUCCESS";
export const GET_SINGLE_SERIES_FAIL = "GET_SINGLE_SERIES_FAIL";

// add video to series
export const ADD_VIDEO_TO_SERIES_REQUEST = "ADD_VIDEO_TO_SERIES_REQUEST";
export const ADD_VIDEO_TO_SERIES_SUCCESS = "ADD_VIDEO_TO_SERIES_SUCCESS";
export const ADD_VIDEO_TO_SERIES_FAIL = "ADD_VIDEO_TO_SERIES_FAIL";
export const ADD_VIDEO_TO_SERIES_RESET = "ADD_VIDEO_TO_SERIES_RESET";

// remove video from series
export const REMOVE_VIDEO_FROM_SERIES_REQUEST =
  "REMOVE_VIDEO_FROM_SERIES_REQUEST";
export const REMOVE_VIDEO_FROM_SERIES_SUCCESS =
  "REMOVE_VIDEO_FROM_SERIES_SUCCESS";
export const REMOVE_VIDEO_FROM_SERIES_FAIL = "REMOVE_VIDEO_FROM_SERIES_FAIL";
export const REMOVE_VIDEO_FROM_SERIES_RESET = "REMOVE_VIDEO_FROM_SERIES_RESET";

// drag & drop series videos
export const DRAG_DROP_SERIES_VIDEOS = "DRAG_DROP_SERIES_VIDEOS";

// get all series
export const GET_ALL_SERIES_REQUEST = "GET_ALL_SERIES_REQUEST";
export const GET_ALL_SERIES_SUCCESS = "GET_ALL_SERIES_SUCCESS";
export const GET_ALL_SERIES_FAIL = "GET_ALL_SERIES_FAIL";

// get all purchased series
export const GET_ALL_PURCHASED_SERIES_REQUEST =
  "GET_ALL_PURCHASED_SERIES_REQUEST";
export const GET_ALL_PURCHASED_SERIES_SUCCESS =
  "GET_ALL_PURCHASED_SERIES_SUCCESS";
export const GET_ALL_PURCHASED_SERIES_FAIL = "GET_ALL_PURCHASED_SERIES_FAIL";

// get series progress
export const GET_SERIES_PROGRESS_REQUEST = "GET_SERIES_PROGRESS_REQUEST";
export const GET_SERIES_PROGRESS_SUCCESS = "GET_SERIES_PROGRESS_SUCCESS";
export const GET_SERIES_PROGRESS_FAIL = "GET_SERIES_PROGRESS_FAIL";

export const GET_VIDEOS_REQUEST = "GET_VIDEOS_REQUEST";
export const GET_VIDEOS_SUCCESS = "GET_VIDEOS_SUCCESS";
export const GET_VIDEOS_FAILED = "GET_VIDEOS_FAILED";


export const GET_KARMA_FILTER_SETTING_REQUEST =
  "GET_KARMA_FILTER_SETTING_REQUEST";
export const GET_KARMA_FILTER_SETTING_SUCCESS =
  "GET_KARMA_FILTER_SETTING_SUCCESS";
export const GET_KARMA_FILTER_SETTING_FAILED =
  "GET_KARMA_FILTER_SETTING_FAILED";

export const CREATE_SCHEDULE_REQUEST = "CREATE_SCHEDULE_REQUEST";
export const CREATE_SCHEDULE_SUCCESS = "CREATE_SCHEDULE_SUCCESS";
export const CREATE_SCHEDULE_FAIL = "CREATE_SCHEDULE_FAIL";

export const GET_SCHEDULE_REQUEST = "GET_SCHEDULE_REQUEST";
export const GET_SCHEDULE_SUCCESS = "GET_SCHEDULE_SUCCESS";
export const GET_SCHEDULE_FAIL = "GET_SCHEDULE_FAIL";

// send connection request
export const SEND_CONNECTION_REQUEST = "SEND_CONNECTION_REQUEST";
export const SEND_CONNECTION_SUCCESS = "SEND_CONNECTION_SUCCESS";
export const SEND_CONNECTION_FAIL = "SEND_CONNECTION_FAIL";
export const GET_CONNECTIONS_REQUEST = "GET_CONNECTION_REQUESTS";
export const GET_CONNECTIONS_SUCCESS = "GET_CONNECTION_SUCCESS";
export const GET_CONNECTIONS_FAIL = "GET_CONNECTION_FAIL";
export const APPROVE_CONNECTION_REQUEST = "APPROVE_CONNECTION_REQUEST";
export const APPROVE_CONNECTION_SUCCESS = "APPROVE_CONNECTION_SUCCESS";
export const APPROVE_CONNECTION_FAIL = "APPROVE_CONNECTION_FAIL";
export const DECLINE_CONNECTION_REQUEST = "DECLINE_CONNECTION_REQUEST";
export const DECLINE_CONNECTION_SUCCESS = "DECLINE_CONNECTION_SUCCESS";
export const DECLINE_CONNECTION_FAIL = "DECLINE_CONNECTION_FAIL";
export const GET_FRIENDS_REQUEST = "GET_FRIENDS_REQUEST";
export const GET_FRIENDS_SUCCESS = "GET_FRIENDS_SUCCESS";
export const GET_FRIENDS_FAIL = "GET_FRIENDS_REQUEST";
export const GET_CONNECTION_STATUS_REQUEST = "GET_CONNECTION_STATUS_REQUEST";
export const GET_CONNECTION_STATUS_SUCCESS = "GET_CONNECTION_STATUS_SUCCESS";
export const GET_CONNECTION_STATUS_FAIL = "GET_CONNECTION_STATUS_FAIL";
export const REMOVE_CONNECTION_REQUEST = "REMOVE_CONNECTION_REQUEST";
export const REMOVE_CONNECTION_SUCCESS = "REMOVE_CONNECTION_SUCCESS";
export const REMOVE_CONNECTION_FAIL = "REMOVE_CONNECTION_FAIL";


// moments
export const UPLOAD_MOMENT_REQUEST = "UPLOAD_MOMENT_REQUEST";
export const UPLOAD_MOMENT_SUCCESS = "UPLOAD_MOMENT_SUCCESS";
export const UPLOAD_MOMENT_FAIL = "UPLOAD_MOMENT_FAIL";

export const UPDATE_MOMENT_REQUEST = "UPDATE_MOMENT_REQUEST";
export const UPDATE_MOMENT_SUCCESS = "UPDATE_MOMENT_SUCCESS";
export const UPDATE_MOMENT_FAIL = "UPDATE_MOMENT_FAIL";

export const GET_SINGLE_MOMENT_REQUEST = "GET_SINGLE_MOMENT_REQUEST";
export const GET_SINGLE_MOMENT_SUCCESS = "GET_SINGLE_MOMENT_SUCCESS";
export const GET_SINGLE_MOMENT_FAIL = "GET_SINGLE_MOMENT_FAIL";

export const DELETE_MOMENT_REQUEST = "DELETE_MOMENT_REQUEST";
export const DELETE_MOMENT_SUCCESS = "DELETE_MOMENT_SUCCESS";
export const DELETE_MOMENT_FAIL = "DELETE_MOMENT_FAIL";

export const GET_ALL_MOMENT_REQUEST = "GET_ALL_MOMENT_REQUEST";
export const GET_ALL_MOMENT_SUCCESS = "GET_ALL_MOMENT_SUCCESS";
export const GET_ALL_MOMENT_FAIL = "GET_ALL_MOMENT_FAIL";

export const TAG_USER_IN_MOMENT_REQUEST = "TAG_USER_IN_MOMENT_REQUEST";
export const TAG_USER_IN_MOMENT_SUCCESS = "TAG_USER_IN_MOMENT_SUCCESS";
export const TAG_USER_IN_MOMENT_FAIL = "TAG_USER_IN_MOMENT_FAIL";
export const TAG_USER_IN_MOMENT_RESET = "TAG_USER_IN_MOMENT_RESET";


export const GET_TAGGED_USERS_OF_MOMENT_REQUEST = "GET_TAGGED_USERS_OF_MOMENT_REQUEST"
export const GET_TAGGED_USERS_OF_MOMENT_SUCCESS = "GET_TAGGED_USERS_OF_MOMENT_SUCCESS"
export const GET_TAGGED_USERS_OF_MOMENT_FAIL = "GET_TAGGED_USERS_OF_MOMENT_FAIL"


export const UPDATE_SCHEDULE_REQUEST = "UPDATE_SCHEDULE_REQUEST";
export const UPDATE_SCHEDULE_SUCCESS = "UPDATE_SCHEDULE_SUCCESS";
export const UPDATE_SCHEDULE_FAIL = "UPDATE_SCHEDULE_FAIL";

export const DELETE_SCHEDULE_REQUEST = "DELETE_SCHEDULE_REQUEST";
export const DELETE_SCHEDULE_SUCCESS = "DELETE_SCHEDULE_SUCCESS";
export const DELETE_SCHEDULE_FAIL = "DELETE_SCHEDULE_FAIL";

export const GET_CATEGORY_BY_CLASS_ID = "GET_CATEGORY_BY_CLASS_ID";
